### ISSUE TITLE
Text is decomposed in parts, instead of treated as Konstant by deriveFamily

### ISSUE THREAD

**Issue by arianvp** [VictorCMiraldo/generics-mrsop#16]
```
             
/home/arian/Documents/UU/Thesis/generics/generics-mrsop-diff/src/Examples/Lua.hs:9:1: error:
    GHC.Prim.ByteArray# is not a declaration
  |          
9 | deriveFamily [t| Stat |]
  | ^^^^^^^^^^^^^^^^^^^^^^^^
```

This error was due to the fact that  `Text`  from the `text` package is an ADT defined in terms of `ByteArray#` . How can I convince the `deriveFamily` machinery to pick it as an atom instead?

**Comment by arianvp** [comment]
Perhaps we should be able to provide our own `consTable` ?

**Comment by VictorCMiraldo** [comment]
yes! we should be able to do that. I will try implementing that today!

**Comment by arianvp** [comment]
We should also derive `TestEquality` for any `Singl` that we generate, as we need that for stuff like generic equality, and diffs.
