### ISSUE TITLE
Support GHC-head

### ISSUE THREAD

**Issue by VictorCMiraldo** [VictorCMiraldo/generics-mrsop#24]
GHC-head complains about our usage of `*`.... Hey, GHC, are you for real? LOL

```
src/Generics/MRSOP/Util.hs:43:23: error:
    Operator applied to too few arguments: *
    With NoStarIsType (implied by TypeOperators), ‘*’ is treated as a regular type operator. 
    Did you mean to use ‘Type’ from Data.Kind instead?
   |
43 | data (:*:) (f :: k -> *) (g :: k -> *) (x :: k)
   |                       ^
```

Seems like a trivial, but painful fix: We did mean to use `Type` from `Data.Kind` GHC. Thanks.

**Comment by monoidal** [comment]
This should be fixed by https://github.com/ghc/ghc/commit/65c186f0fdde95fd7c63ab9bd9b33a0213dba7d1.

**Comment by VictorCMiraldo** [comment]
Great, thanks!
