### ISSUE TITLE
Implement Attribute Grammars

### ISSUE THREAD

**Issue by arianvp** [VictorCMiraldo/generics-mrsop#28]
Now that we can do catamorphisms and paramorphisms over  _mutal recursive_ datatypes,
we actually have enough power to write an embedded DSL for Attribute Grammars.

@serras and I brainstormed a bit about this today.

Commit here: https://github.com/VictorCMiraldo/generics-mrsop/commit/835de82f8a744a09a742f606f3d96b63724e59db

Branch here: https://github.com/VictorCMiraldo/generics-mrsop/compare/arian-dev

**Comment by arianvp** [comment]
![img_20180724_165350](https://user-images.githubusercontent.com/628387/43149308-707e6836-8f67-11e8-839b-013ac1ba4484.jpg)

**Comment by arianvp** [comment]
So I have
```haskell

-- | Annotate each node with the number of subtrees
sizeGeneric' ::
     forall ki codes ix. Fix ki codes ix -> AnnFix ki codes (Const (Sum Int)) ix
sizeGeneric' = synthesize sizeAlgebra
  where
    sizeAlgebra :: Rep ki (Const (Sum Int)) xs -> Const (Sum Int) iy
    sizeAlgebra = 
          mappend (Const 1) . elimRep (const mempty) (Const . getConst) mconcat

-- | Count the number of nodes
sizeGeneric :: forall ki codes ix. Fix ki codes ix -> Const (Sum Int) ix
sizeGeneric = cata sizeAlgebra
  where
    sizeAlgebra :: Rep ki (Const (Sum Int)) xs -> Const (Sum Int) iy
    sizeAlgebra = 
          mappend (Const 1) . elimRep (const mempty) (Const . getConst) mconcat
```

now, and `sizeAlgebra` is clearly the same. However, if I move
`sizeAlgebra` to the toplevel I get the following obscure error, which must be a _ghc bug_ or
something
```haskell
/home/arian/Documents/UU/Thesis/generics/generics-mrsop/src/Generics/MRSOP/AG.hs:73:27: error:
    • Expected kind ‘Rep ki (Const (Sum Int)) (Lkup iy codes)
                     -> Const (Sum Int) iy’,
        but ‘sizeAlgebra’ has kind ‘Rep
                                      ki (Const (Sum Int)) (Lkup iy codes)
                                    -> Const (Sum Int) iy’
    • In the first argument of ‘synthesize’, namely ‘sizeAlgebra’
      In the expression: synthesize sizeAlgebra
      In an equation for ‘sizeGeneric'’:
          sizeGeneric'
            = synthesize sizeAlgebra
            where
   |
73 | sizeGeneric' = synthesize sizeAlgebra
   |                           ^^^^^^^^^^^
```

It's talking about the _kind_ of the function, which is totally weird...  as functions do not have kinds.
and  it basically says  "Expected a, but got a"

**Comment by serras** [comment]
Since now kinds and types are the same, GHC sometimes prints the wrong term.

Trey with -fprint-explicit-foralls and -fprint-explicit-kinds. It might be
inferring a wrong implicit kind somewhere, leading to the error.

**Comment by arianvp** [comment]
`PolyKinds` did the job.    The `Const` datatype wasn't polykinded otherwise, and wouldn't be of kind `Nat -> *`

**Comment by arianvp** [comment]
Okay this is just poetry!  This stuff is really, really cool.

https://github.com/VictorCMiraldo/generics-mrsop/blob/d40506fc4252a93b1d96de893d3905a2907bcf12/src/Generics/MRSOP/AG.hs#L77-L97

**Comment by VictorCMiraldo** [comment]
@arianvp , this is already done right? can we close this issue?

**Comment by VictorCMiraldo** [comment]
Discussing with @arianvp , this is closed.
