### ISSUE TITLE
Fix is AnnFix

### ISSUE THREAD

**Issue by VictorCMiraldo** [VictorCMiraldo/generics-mrsop#35]
Looking at f5d6348c9f767f8e52026cf03d80f82d63d7f23a , it makes sense to drop `Fix` altogether.

For that, we'd need a type synonym and a pattern synonym to make the rest of the code
compile as is. @arianvp , feel free to throw in a PR when you're back from holidays!

**Comment by arianvp** [comment]
That's what that commit does! It adds a pattern synonym and makes the rest of the code compile as is :)
