### ISSUE TITLE
Depend on sop-core

### ISSUE THREAD

**Issue by arianvp** [VictorCMiraldo/generics-mrsop#41]
http://hackage.haskell.org/package/sop-core

Generics-sop has extracted all its utility functors like NS and NP to a separate package.  Would be nice to use those versions.

**Comment by VictorCMiraldo** [comment]
We really only care about the `NS` and `NP` types. For the sake of compatibility with other libraries in the future, I think we could just `import Data.SOP (NP(..))` in `Generics.MRSOP.Base.NP` and the same in `NS`.

**Comment by arianvp** [comment]
Yes. That is exactly what I wanted to suggest :)

**Comment by VictorCMiraldo** [comment]
For the sake of documenting; this does conflict with #39 !

I'm of the opinion that #39 will eventually become obsolete once they fix GHC's bug. Nevertheless,
if the 8.8 release does not fix it, I will give a shot at #39, which will break the `sop-core` dependency.

**Comment by VictorCMiraldo** [comment]
We have decided we will not add an extra dependency for two datatypes only.

**Comment by VictorCMiraldo** [comment]
After discussing with Andres at ICFP, I was convinced it is better to depend on `sop-core` than to
roll my own `NS` and `NP` datatypes.

**Comment by VictorCMiraldo** [comment]
As usual; not so straight forward. I gave it a quick go at c6bd21b1329d866332c67e57f1a1f26a1f19b384 but then got stuck on a typeclass hell.

`Data.SOP.Constraint` defines the following instances for `NS` and `NP`:

```
instance (All (Compose Show f) xs) => Show (NS f xs) where ...
instance (All (Compose Eq f) xs) => Eq (NS f xs) where ...
```

Which makes sense, but are harder to thread through `generics-mrsop`, where
we abstracted it differently, by the means of the `showHO`.

**Comment by serras** [comment]
Where do the problems arise more concretely?

**Comment by VictorCMiraldo** [comment]
I'm not 100% yet; I'm trying to remove the `ShowHO` and `EqHO` typeclasses we had. I just made
them into the following constraint-synonyms:

```haskell
type EqHO   f = forall x . Eq (f x)
type ShowHO f = forall x . Show (f x)
```

In the old `Generics.MRSOP.Zippers.Deep` we'd have to carry some constraint in the `Ctx` datatype.
I just removed the module as the shallow zippers should suffice.

I'm now trying to compile `generics-mrsop-gdiff` and `hdiff`; if I succeed on these, I'd happily drop `EqHO` and `ShowHO` and stick with the quantified constraints versions above and unify everything
with `sop-core`.

**Comment by VictorCMiraldo** [comment]
@serras 

The process has been mainly mechanic so far; We will need to add things like
the following instance to `mrsop`, though.

```haskell
type EqHO   f = forall x . Eq (f x)
instance (EqHO f , EqHO g) => Eq ((f :*: g) x) where
  (==) (fx :*: gx) (fy :*: gy) = fx == fy && gx == gy
```

**Comment by serras** [comment]
I thinl you can even abstract the `EqHO` type as:

```haskell
type HO (c :: r -> Constraint) (f :: k -> r) = forall (x :: k). c (f x)
instance (HO Eq f, HO Eq g) => Eq ((f :*: g) x) where ...
```

Now you don't need a different `ConstraintHO` for each constraint.

**Comment by VictorCMiraldo** [comment]
That makes sense; It's just that a good amount of code already has `EqHO` and `ShowHO` spread through it.

In any way; if I understand `-XQuantifiedConstraints`, this shouldn't be different from our
manual handling of higher-order though our (old) `EqHO`.

**Comment by serras** [comment]
You can always define `EqHO` as `HO Eq` and keep the code the same.

Note however that `-XQuantifiedConstraints` sometimes asks for more than a higher-order version. In the case of something like `NP`, you can ask for `Eq (f x)` for every `x` in a type-level list; if you ask for `forall x. Eq (f x)` this requires *for every* `x` in `Type`.

**Comment by serras** [comment]
> @serras , I got some impredicative polymorphism error right [here](https://github.com/VictorCMiraldo/hdiff/commit/95382d7e85e2f13cefe55531fcad4e11a1b17ef8#diff-d60afcb1627d6190fc1d637a218223f2L66), for which I had to pull the quantified constraints out
> and distribute them by hand. Not sure if this was supposed to happen or if type annotations would fix this.

Yes, there seems to be some weird things happening when you abstract over constraints with `forall`s. Something they "count" as quantified constraints , and everything is fine, sometimes they are rank-n types, and then GHC starts asking for impredicative polymorphism.

I guess the best solution is what you are doing: just thread the constraints by hand.
