### ISSUE TITLE
Drop Monad constraint on mapNPM and friends

### ISSUE THREAD

**Issue by arianvp** [VictorCMiraldo/generics-mrsop#43]
https://github.com/VictorCMiraldo/generics-mrsop/blob/master/src/Generics/MRSOP/Base/NP.hs#L48

They can live with just an `Applicative` constraint. Perhaps to be consistent we should name them `traverse` instead of `mapM` as well

**Comment by VictorCMiraldo** [comment]
Pardon the delay in answering this.

I disagree purely out of stuborness: `Applicative` should **not** be a superclass of `Monad` and therefore,
I stick with `Monad`. 

The reason is that given a monad always gives rise to TWO applicatives:

```haskell
apL :: (Monad m) => m (a -> b) -> m a -> m b
apL mf ma = do
  f <- mf
  a <- ma
  return (f a)

apR :: (Monad m) => m (a -> b) -> m a -> m b
apR mf ma = do
  a <- ma
  f <- mf
  return (f a)
```
These two are only equal when the monad is strong.
