### ISSUE TITLE
Can only derive one datatype per module

### ISSUE THREAD

**Issue by arianvp** [VictorCMiraldo/generics-mrsop#47]

**Comment by VictorCMiraldo** [comment]
True! This issue is also coupled with #34 and #22 

Solving the three of them should suffice for a new minor release. 

@arianvp , do you need this solved quickly or can you just split datatypes in different modules
a live with this for a while?

**Comment by arianvp** [comment]
This is not a blocker for me. Just something I ran into while messing around

**Comment by VictorCMiraldo** [comment]
Awesome, I'll think about a good fix for this, I'm glad we don't have to rush it.

I think the ideal would be to have more control over how the names
are generated in the TH interface. for example:

```haskell
data BlaBla = ...

deriveFamily ''OpqTypes [t| BlaBla |] names

names :: NamingStructure
names = def { familyName = ("BlaBla_" ++)
            , codesName = ("__" ++) 
            , genPatternSyns = True
            }
```

What do you think?

**Comment by VictorCMiraldo** [comment]
The naming machinery is not as fancy as proposed [here](https://github.com/VictorCMiraldo/generics-mrsop/issues/47#issuecomment-478582415), but this is no longer an issue. I'll close this and open another feature request for the fancy naming machinery.
