### ISSUE TITLE
Bring back `ShowHO` and `EqHO` as we had before

### ISSUE THREAD

**Issue by VictorCMiraldo** [VictorCMiraldo/generics-mrsop#58]
As it turns out, using `NS` and `NP` from `sop-core` came with an annoying difficulty. The handling of typeclasses is more complicated than what it needs to be.

I think we need to use `NS` and `NP` from `sop-core`, granted. But we should restore
`EqHO` and `ShowHO` like before:

```haskell
class EqHO f where
  eqHO :: f x -> f x -> Bool
```

This makes the treatment of typeclasses much easier for our particular context. One example
of a difficult scenario is in [here](https://github.com/arianvp/generics-mrsop-gdiff/blob/candidate-0.0.2/src/Generics/MRSOP/STDiff/Enum.hs#L58), where we can't just use `(==)` because
`sop-core`'s instance requires an instance of `All (Compose Eq (NA ki (Fix ki codes))) (Lkup c sum)`, however, `c` here is a local type variable that comes from a call to `sop`. 
Here's a smaller outline:

```haskell
difficult :: Fix ki codes ix -> Bool
difficult x = case sop x of
                  Tag cx px -> px == px
```

The code above will not compile; We would need to propagate the `All (Compose ...)` constraint
to the `Tag` constructor to make it usable, and that's solely for `Eq`; if we need `Eq` and `Show`, then we'd need to propagate both constraints and so on and so forth.

@serras , do you know of a better alternative?

The `EqHO` approach we had before would allow a third party to easily provide typeclasses
working over generic code, this current approach is not so lightweight.

**Comment by VictorCMiraldo** [comment]
Related to #42 #41

**Comment by serras** [comment]
I am not at all surprised. I've had so many cases where I start using `All` and then it falls short at some point. One idea I have player with is to make versions of `NP` and `NS` parametric on a constraint, like:

```haskell
data NP (c :: k -> Constraint) (f :: k -> Type) (xs :: [k]) where
  (:*) :: c x => f x -> NP c f xs -> NP c f (x ': xs)
  Nil :: NP c f '[]
```

but then you might be pushing `QuantifiedConstraints` to their limits.

**Comment by VictorCMiraldo** [comment]
Yeah, I start to dislike `All` very much; it really hinders the usage of the library with overcompliated typeclass engineering and most of the times, it doesn't add that much safety. 

I like having the same `NS` and `NP` as `sop-core`, because it allows us to port mrsop functionality back and forth easily, I think the best design really is to just go back to using our versions of `EqHO` and `ShowHO` with mrsop but using `NS` and `NP` from `sop-core`; this would also drop the need for `-XQuantifiedConstraints`. 

I will sleep on it though; if I feel inspired and sure this is the option; I'll implement on monday and release another version of mrsop; it is slowly converging to something more stable! :)
